global:
  scrape_interval: 5s

rule_files:
  - "/etc/prometheus/rules.yml"

scrape_configs:
  - job_name: 'crm-order-system'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8080']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']